#!/bin/sh
echo "This shell script will allow you to make your own iconset."
echo
echo -n "Please enter the name you'd like to call your set: "
read foo

echo -n Creating $foo/...
cp -r BoringBlack $foo
echo done.
echo
echo -n "Please enter your name (for aboutbox purposes): "
read name
echo #define CREDIT \"$name\" > $foo/credit.h
echo Done!
echo Now you may edit the files in \'$foo\' to your liking.
