module GNOME
{
	interface CDAudio
	{
		enum TimeFormat
		{
			TrackElapsed,
			TrackRemaining,
			DiscElapsed,
			DiscRemaining
		};

		enum StatusType
		{
			Playing,
			Stopped,
			Paused,
			NoDisc,
			Error
		};

		enum ErrorType
		{
			NoError,
			IOError, /* If there's an ioctl error or likewise */
			InitFirst /* If you haven't called init first */
		};

		/* returned by init_cd */
		struct CD
		{
			short fd;
			string path;
		};
		
		/* this is a struct that is filled with information */
		struct Info
		{
			StatusType status;
			TimeFormat format;
			short min, sec; /* time in format 'format' */
		
			short current_track;
		};

		CD	init_cd(in string path);
		ErrorType	play_cd(in CD cd, in short start_track, in short end_track);
		ErrorType 	pause_cd(in CD cd);
		ErrorType	stop_cd(in CD cd);
		ErrorType	eject_cd(in CD cd);
		
		ErrorType	get_info(in CD cd, out Info info);

		ErrorType	get_disc_titles(in CD cd, out string artist, out string album, out string title);
		ErrorType	get_track_title(in CD cd, in short track, out short title);
	};

	interface cdp 
	{
		void notify_name (in long tag, in string cd_name);
	};

	interface cddb_backend
	{
		void query (in string specifier, in cdp parent);
	};
};
