module GNOME
{
	struct CDAudio_Info
	{
		short fd;
		string path;
		
		short status;
	};

	interface CDAudio
	{
		enum TimeFormat
		{
			TRACK_ELAPSED,
			TRACK_REMAINING,
			DISC_ELAPSED,
			DISC_REMAINING
		};
	
		CDAudio_Info	init_cd(in string path, out long result);
		void	play_cd(in short start_track, in short end_track, out long result);
		void 	pause_cd();
		void	stop_cd();
		void	eject_cd();
		
		void	get_time(in TimeFormat format, out short min, out short sec);
		void	get_disc_info(out string artist, out string album, out string title);
	};
};
